name: a-very-simple-workflow

# Manual Trigger
on:
  workflow_dispatch:

jobs:
  
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Send Hello World
      run: |
        echo "Hello World!"
