name: azure-ml-pipeline

on:
  push:
    branches:
      - main

jobs:

  train-model:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Repository
        id: checkout_repository
        uses: actions/checkout@v2

      - name: Trigger ML Job
        run: |
        az ml job create --file jobs/hello-string.yml 
