name: azure-run-ml-manual

on:
  workflow_dispatch:

jobs:

  train-model:
    runs-on: ubuntu-latest
    steps:

      - name: Check Repository
        uses: actions/checkout@v2

      - name: Install AZ ML Extension
        run:  az extension add -n ml -y

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{secrets.AZURE_CREDENTIALS}}' 

      - name: Set current directory
        run: cd src 

      - name: Trigger ML Job
        run: |
        az ml job create --file jobs/iris.yml -g grcMlRg -w grcMlWs